### ISSUE TITLE
Issues reported during HIDAP training in Mwanza, Tanzania (10-11 August 2017)

### ISSUE THREAD

**Issue by lukawanjohi** [omarbenites/hidap_issues#103]
1.	The MS word report generated by HIDAP throws a waning although it opens just fine. 
2.	Sometimes the MS word report will not be generated if you have an active MS Word window
3.	String data in the HIDAP Fieldbook crashes the system.

**Comment by cipriuhq** [comment]
Hi Luka, thanks for reporting these issues here in the github repository.

1. About the MSWord files, it show messages when HIDAP is writing word docs using Markdown. It's just an issue from MSWord.
![image](https://user-images.githubusercontent.com/29386384/30546166-6f78e326-9c51-11e7-9299-dafc834d8469.png)

2. I will talk with Raul about it. 

3. Generally, it does not support string data.  In the potato trait dictionary we define some cualitative variable does support strings data.  Maybe in november we can talk about this for sweetpotato.

Regards.
