### ISSUE TITLE
Include download template in "Material Management"

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#106]
Currently the only section to download an empty template is under "Fieldbook management":
![image](https://user-images.githubusercontent.com/25850965/30864888-94c50af2-a29a-11e7-8a0e-53abd6268261.png)
This option should be under "Material Management":
![image](https://user-images.githubusercontent.com/25850965/30865186-882eff40-a29b-11e7-951d-5c0190c20942.png)

*Elisa Salas*

**Comment by cipriuhq** [comment]
Creo que esta sección se debe mantener, ya que este template es solo para genotipos que no están registrados en la BD.
