### ISSUE TITLE
Add protocols to HIDAP documents section

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#107]
In the "HIDAP documents" section:
![image](https://user-images.githubusercontent.com/25850965/30865255-b9a99fe4-a29b-11e7-9018-4f2e5f71da19.png)
add the protocols as well:
https://research.cip.cgiar.org/potatoknowledge/protocols.php

*Elisa Salas*

**Comment by cipriuhq** [comment]
Dichos documentos en conjunto son muy pesados, y harán que el instalador se vuelva mas pesado aun.

**Comment by STOALM** [comment]
Creo que Elisa sólo se refiere al link de ABS

**Comment by cipriuhq** [comment]
Agrege ese y el de camote tambien.
http://www.sweetpotatoknowledge.org/sections/research-procedures-protocols/

Solucionado.
