### ISSUE TITLE
Installation sheet bug

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#108]
First, when creating a fieldbook with a statistical design and downloading it, there is no problem.
![image](https://user-images.githubusercontent.com/25850965/30922504-f49ecab0-a36e-11e7-931a-f7144144dd84.png)
Then, when creating a second fieldbook with a different statistical design, the previous information still shows in the "Installation sheet"
![image](https://user-images.githubusercontent.com/25850965/30922571-23c4595e-a36f-11e7-826f-d8c67b1fd1a2.png)
![image](https://user-images.githubusercontent.com/25850965/30922609-3eda3bb4-a36f-11e7-918f-5cc62787228f.png)

**Comment by cipriuhq** [comment]
Now solved. :soccer:
