### ISSUE TITLE
Spelling in Statistical Design

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#118]
Wescott design (WD):

![image](https://user-images.githubusercontent.com/25850965/31775364-05406b44-b4ae-11e7-8f15-838774c818d7.png)

Number of rows of the field, change to: "Number of rows *in* the field"

Verify if your material have these checks: "Verify if your material *list has* these checks"

**Comment by omarbenites** [comment]
Now fixed! :+1:
