### ISSUE TITLE
valores fuera de rango

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#120]
Para el chequeo de datos se han definido dos tipos de reglas:

- Estadísticas para detectar outliers.
- No estadísticas para detectar valores fuera de rango.

Sobre el segundo grupo. Ciertas variables (como algunas evaluaciones que van de 1 a 9) tienen rangos bien definidos, pero otras, como los rendimientos, no. A mi juicio lo único que podemos poner como valor inválido a un rendimiento son los valores negativos. Poner un límite máximo creo que tiene inconvenientes:

- Es subjetivo en el sentido más amplio. No hay ningún fundamento técnico para definir 100 o 1000 o 10000 como límite máximo.
- En consecuencia, no aporta mucho.

En el ejemplo siguiente (los datos que estoy trabajando) parece que se ha decidido que no pueden haber más de 200 o 250 raíces por parcela, y entones en mis libros salen pintadas casi todas, aun cuando todos los valores son perfectamente posibles (el experimento tiene 120 plantas).
 
![screenshot 2017-10-19 15 59 38](https://user-images.githubusercontent.com/7216359/31794398-d8287e64-b4e7-11e7-8219-174b448bef3b.png)

**Comment by omarbenites** [comment]
Solucionado en hidap y en las odontologías de camote.
