### ISSUE TITLE
dmry no se calcula

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#121]
dmry no se calcula (depende de rytha y dm)
![screenshot 2017-10-19 16 26 41](https://user-images.githubusercontent.com/7216359/31795253-bbdcf44e-b4ea-11e7-888b-dcc47eade771.png)

**Comment by omarbenites** [comment]
Hola Raul, un favor tendras ese dataset para hacer el test. Lo subes por aqui si puedes.
