### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#130]
Fieldbook preview bug when scrolling to the right:

![image](https://user-images.githubusercontent.com/25850965/34949879-7255be98-f9df-11e7-829a-54e277cf7daf.png)
![image](https://user-images.githubusercontent.com/25850965/34949909-8f3cbc14-f9df-11e7-8c67-2abc73a82748.png)
![image](https://user-images.githubusercontent.com/25850965/34949923-97006388-f9df-11e7-8962-888db3a08cd1.png)

**Comment by omarbenites** [comment]
Just an issues from rhandsontable library in JS.
