### ISSUE TITLE
Distribution data

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#134]
Material management/Distribution data/Connect/Search results:
Temporary bug displays and quickly fades away
![image](https://user-images.githubusercontent.com/25850965/35045922-6bfa507e-fb63-11e7-867f-e0ec72713021.png)

**Comment by omarbenites** [comment]
I need to talk with database gang and discuss SQL query to update Distributional database. 👀 ⚠️

**Comment by omarbenites** [comment]
Related to #134 issues https://github.com/CIP-RIU/hidap_issues/issues/134.
