### ISSUE TITLE
About

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#135]
First sentence, delete practices: "which include"
Add space before "("
![image](https://user-images.githubusercontent.com/25850965/35152831-01427078-fcf2-11e7-9374-b44030bf89df.png)

**Comment by omarbenites** [comment]
It is solved, but requiere to upload into RIU CRAN

**Comment by omarbenites** [comment]
The next installer will fix this issue.

**Comment by STOALM** [comment]
✓
