### ISSUE TITLE
HIDAP documents

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#138]
When opening the PVS documentation (dictionary)
![image](https://user-images.githubusercontent.com/25850965/35569257-bd7a6dea-0599-11e8-8247-0c67009e8b84.png)
This window shows up:
![image](https://user-images.githubusercontent.com/25850965/35569250-b7b627c8-0599-11e8-9059-8a8d83469e15.png)

**Comment by omarbenites** [comment]
Please, check in the new version whether this issues is still appearing, otherwise, we may close it. :point_up:

**Comment by omarbenites** [comment]
@STOALM I have just solved this issues, please update it . Thanks!.  :potato: :sweet_potato:
