### ISSUE TITLE
Filters after checking

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#139]
These sheets get filters after checking the fieldbook:
minimal:
![image](https://user-images.githubusercontent.com/25850965/36167926-7cdd859c-10c5-11e8-87c8-bf4b1d469bbc.png)
Installation:
![image](https://user-images.githubusercontent.com/25850965/36167944-90b23004-10c5-11e8-93f1-1455b1540323.png)
var list:
![image](https://user-images.githubusercontent.com/25850965/36167933-852afbb2-10c5-11e8-849f-966f062bc579.png)

**Comment by omarbenites** [comment]
So, those filters appear after checking data (check module) ?. I put those filters in the fieldbook design.
