### ISSUE TITLE
Additional heading

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#141]
Additional "FEMLAE" heading when checking LxT fieldbook:
![image](https://user-images.githubusercontent.com/25850965/36429726-78cd8194-1621-11e8-911e-a691088f1135.png)
Fieldbook attached:
[PTYield072013_CIPSRM_exp2 - Copy.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1740459/PTYield072013_CIPSRM_exp2.-.Copy.xlsx)

**Comment by omarbenites** [comment]
The error was found in the  `traitools`  package, specifically in the function ``col_render_trait``. It was declared. 

![image](https://user-images.githubusercontent.com/5264796/36605738-a29cf606-188f-11e8-89a4-16ff912820e4.png)


Now it's solved. Update in HiDAP Update.
