### ISSUE TITLE
Installation sheet

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#142]
When creating different fieldbooks, the information such as: factor_name gets copied onto the rest of the fieldbooks even when the statistical design doesn't apply.
-Past issue-
![image](https://user-images.githubusercontent.com/25850965/36695511-92655a58-1b0f-11e8-8a46-088cf3752a50.png)

**Comment by omarbenites** [comment]
Fixed bug. The next installler would include it.

**Comment by STOALM** [comment]
✓
