### ISSUE TITLE
Agregar mensaje para actualizar Bases de datos

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#144]
"Warning: this may take more than 5 minutes" Agregar mensaje abajo del boton de "Synchronize material lists" en Material Management
![image](https://user-images.githubusercontent.com/25850965/36734673-38075870-1ba2-11e8-8d74-f8a71469bc43.png)

**Comment by STOALM** [comment]
![image](https://user-images.githubusercontent.com/25850965/36864412-9dccbdc6-1d5a-11e8-8cab-70161c5793a6.png)
Creo que es muy larga la explicación, tal vez sólo "This may take more than 5 minutes" porque si ponemos about es como darle un ±1min. Y usar "may" en vez de "will" para indicar posibilidad en vez de estar seguros de que tomará tanto tiempo, porque también depende de las máquinas. Además abajo ya explica que está cargando:
![image](https://user-images.githubusercontent.com/25850965/36864505-dac8d48a-1d5a-11e8-9c9c-ae7ea0417909.png)
Un mensajito pequeño creo que es sufi

**Comment by omarbenites** [comment]
Listo, lo acabo de incorporar la mejora para el nuevo instalador.
