### ISSUE TITLE
Agregar mensaje al inicio

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#147]
Al abrir HIDAP agregar mensaje en la esquina esquina inferior derecha 'Loading' ya que demora un poco por el HIDAP Network

**Comment by omarbenites** [comment]
Se le agrego en la siguiente versión un mensaje de `loading modules` cuando carga HiDAP.

**Comment by STOALM** [comment]
Primero sale "Loading modules"
Y luego "Loading HiDAP... Loading modules"
creo que mejor se vería sólo uno de ellos
![image](https://user-images.githubusercontent.com/25850965/36864120-b8ac4770-1d59-11e8-9634-31b5a9753ffb.png)

**Comment by omarbenites** [comment]
Acabo de incorporar esta mejora.
