### ISSUE TITLE
Material management/Manage list/Export

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#148]
Sin seleccionar una lista y dando click en Export se abre una nueva ventana con:
![image](https://user-images.githubusercontent.com/25850965/36735453-42864660-1ba4-11e8-9b22-c7073eb3d4d0.png)

**Comment by omarbenites** [comment]
Arreglado para la siguiente versión de HIDAP.

**Comment by STOALM** [comment]
✓
