### ISSUE TITLE
Error de tipeo en manage lists

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#149]
Al crear lista de clones se agrega "clon", pero al crear lista de familias "clone". Estandarizar:
![image](https://user-images.githubusercontent.com/25850965/36737608-784d7bb0-1ba9-11e8-93f7-02c257c4e127.png)

**Comment by omarbenites** [comment]
This issues is fixed. The next hidap installer will include it.

**Comment by STOALM** [comment]
✓
