### ISSUE TITLE
No calcula "ASC_DW"

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#155]
![image](https://user-images.githubusercontent.com/25850965/36755318-d3fa8874-1bd9-11e8-9cff-63db2b0697ec.png)

**Comment by omarbenites** [comment]
Hola Jazmín, un favor, ¿Tienes el dataset para probar en HIDAP?

**Comment by STOALM** [comment]
Aquí: [PTVitamin C092017_CIPHQ_RCBD_TVIT.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1789563/PTVitamin.C092017_CIPHQ_RCBD_TVIT.xlsx)

**Comment by omarbenites** [comment]
Lo corrí en la nueva versión, y ahora si pudo calcular. Me avisas si hay otra formula con ese problema. :potato:
