### ISSUE TITLE
Mensaje de Update Packages

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#158]
Mensaje muy agresivo visualmente y con typo, tal vez cambiarlo a minúsculas y poner: "Quit HiDAP to finish the update" ya sin decirles que lo deben reabrir.
![image](https://user-images.githubusercontent.com/25850965/36853397-6cd4a4a4-1d3c-11e8-8be4-10a074b5e1ff.png)

**Comment by omarbenites** [comment]
Jaja... :fist_oncoming: . Me parece bien, pondré `Close HiDAP to finish the update`

**Comment by omarbenites** [comment]
Incluido para  el siguiente instalador.
