### ISSUE TITLE
Plant installation doesn't calculate plot size

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#16]
Module: Fieldbook management / New fieldbook / Plant Installation / Plot size (only in Special Modules: PVS)

It isn't calculating the plot size correctly.

Formula: 
Plot size = Number of plants per row * Distance between plants (m) * Number of rows per plot/pot * Distance between rows (m)

Plot size = 10 * 0.2 * 2 *0.7 = 2.8

Image:
![image](https://cloud.githubusercontent.com/assets/25850965/23664585/ef71ec52-0323-11e7-87b4-a5024a6d73c1.png)

**Comment by omarbenites** [comment]
Now it's fixed. Thx :+1:
