### ISSUE TITLE
PTLB+WD

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#161]
Al correr el libro adjunto sale este error:
Diseño WD
[PTLate blight042015_KUNMING_PTLB_WD.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1794760/PTLate.blight042015_KUNMING_PTLB_WD.xlsx)
![image](https://user-images.githubusercontent.com/25850965/37175711-58ddff0c-22e8-11e8-9268-e8dd84d0b556.png)

**Comment by omarbenites** [comment]
El error se debe a que no hay la columna de repetición `REP`.  El diseño Westcott no tiene repetición, son sólo filas y columnas; por lo tanto no se puede calcular SAUDPC. Voy a colocar un aviso en HIDAP.
