### ISSUE TITLE
Var_list sweetpotato

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#168]
Obsérvese la información debajo de Ontology para el caso de camote
![image](https://user-images.githubusercontent.com/25850965/37310145-0865d988-2611-11e8-9688-0422880df100.png)

**Comment by omarbenites** [comment]
Hay que preguntarle a Vilma, ya que en el data diccionario de internet no aparece y el HIDAP se alimenta de alli.

**Comment by STOALM** [comment]
Pendiente: preguntar a Vilma

**Comment by omarbenites** [comment]
Sabes si vilmex te dijo algo?

**Comment by STOALM** [comment]
ya se agregó bajo el heading "Variable name" en el data dictionary

**Comment by omarbenites** [comment]
El diccionario fue actualizado por Jazmin. Now it's closed.
