### ISSUE TITLE
Localidades

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#169]
Federico y yo creemos que esta localidad CIPSRM-2 a 964 msnm no existe.
![screenshot 2018-03-13 09 01 43](https://user-images.githubusercontent.com/7216359/37346386-2f712ad2-269d-11e8-8d9b-406cedf6b212.png)

**Comment by omarbenites** [comment]
?Cuál es la elevación exacta de San Ramón2?. Así lo modifico.

**Comment by reyzaguirre** [comment]
840
