### ISSUE TITLE
Shouldn't show calculated variables

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#17]
Module: Fieldbook management / New fieldbook

When a fieldbook is created in the sheet "F9_Clones_Select_Storage" the calculated variables are being displayed, when they shouldn't:

Image:
![image](https://cloud.githubusercontent.com/assets/25850965/23672141/b28c4900-033b-11e7-85bb-514083282d3c.png)

**Comment by omarbenites** [comment]
It's fixed now. Thnx :+1:
