### ISSUE TITLE
Quality Sweetpotato

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#172]
Cambiar fórmula de DM: Storage root dry matter content percent a DM = (DMD / DMF) * 100
PD. Ya se cambió en el excel del data dictionary

**Comment by omarbenites** [comment]
?En donde esta esa formula en el diccionario?

**Comment by STOALM** [comment]
![image](https://user-images.githubusercontent.com/25850965/37656112-2052c4f2-2c15-11e8-8642-c27c71859ba3.png)

**Comment by omarbenites** [comment]
actualmente el HIDAP calcula mal esta formula?

**Comment by STOALM** [comment]
sí, ya la cambié en el data dictionary de HIDAP
