### ISSUE TITLE
Drought + AD

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#173]
Error al crear libro de sequía con diseño aumentado:
![image](https://user-images.githubusercontent.com/25850965/37605536-6180594e-2b61-11e8-8689-32ab15f0d502.png)
![image](https://user-images.githubusercontent.com/25850965/37605544-66de5ce2-2b61-11e8-9400-750418558488.png)

**Comment by omarbenites** [comment]
1

**Comment by STOALM** [comment]
ya lo crear con el nuevo instalador?
