### ISSUE TITLE
EDA error

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#175]
No genera gráfico si algún clon no tiene valores en la variable seleccionada:
![image](https://user-images.githubusercontent.com/25850965/37618953-d8b68172-2b85-11e8-91b5-9943f6c6f345.png)

**Comment by omarbenites** [comment]
?Tendrás el fieldbook de este ejemplo?

**Comment by STOALM** [comment]
[PTBulking012018_CIPHQ_ABD_PTBM.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1838239/PTBulking012018_CIPHQ_ABD_PTBM.xlsx)

**Comment by omarbenites** [comment]
El error es que se debe seleccionar un trait y no un factor (INSTN)
![image](https://user-images.githubusercontent.com/5264796/37790841-9f5599de-2dd5-11e8-8848-b0b5810e36e5.png)
