### ISSUE TITLE
EDA error 2

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#176]
Poner un mensaje más claro para este error:
![image](https://user-images.githubusercontent.com/25850965/37619162-a2b8a25c-2b86-11e8-9d9c-4424907d2a7d.png)

**Comment by omarbenites** [comment]
?Tendrás el fieldbook de este ejemplo?

**Comment by STOALM** [comment]
[PTBulking012018_CIPHQ_ABD_PTBM.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1838246/PTBulking012018_CIPHQ_ABD_PTBM.xlsx)

**Comment by omarbenites** [comment]
El problema es que la columna no tiene ningún dato. Se podría agregar un mensaje de que la columna esta vacia.
![image](https://user-images.githubusercontent.com/5264796/37791073-4149c954-2dd6-11e8-9b16-0ae94f70c2a5.png)
