### ISSUE TITLE
EDA scatterplot

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#177]
En este caso no debería haber 3 gráficos?
![image](https://user-images.githubusercontent.com/25850965/37620923-954d6b66-2b8b-11e8-9a5b-bffd4eae8fb8.png)

**Comment by STOALM** [comment]
Con esta combinación sí salen 3 gráficos:
![image](https://user-images.githubusercontent.com/25850965/37623448-becdb980-2b92-11e8-89c1-8d6a1325c8f8.png)

**Comment by omarbenites** [comment]
?Tienes el fieldbook del primer screenshoot?. Parece que es por la cantidad de observaciones y ambas son variables cateregoricas. Por lo menos debe haber una variable cuantitativa, como en el segundo ejemplo.

**Comment by STOALM** [comment]
Es el mismo libro para los dos.
[PTYield052002_CIPHQ.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1838223/PTYield052002_CIPHQ.xlsx)

**Comment by omarbenites** [comment]
Self note: create new `eda4plant` :package:  package
