### ISSUE TITLE
Creates a different header instead of using the one already there

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#18]
Module: Fieldbook management / Check fieldbook / Form_9

I have these headers:

![image](https://cloud.githubusercontent.com/assets/25850965/23672854/18fc0fb6-033e-11e7-85c9-686852b5c7ac.png)

But when checking the fieldbook a new gets created:

![image](https://cloud.githubusercontent.com/assets/25850965/23672870/27ed2c44-033e-11e7-9959-3809a828c87a.png)

It should only be "PCT_WOMEN, and not PCT_WOMAN"

**Comment by omarbenites** [comment]
Now fixed. Try in the next version and re-open the issue whether persist this problem.
