### ISSUE TITLE
Mensaje en español en reporte Elston index

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#180]
1) Mensaje en español en el reporte
2) Además en opción html para el reporte, abre 2 veces
3) Si es posible, se podría cambiar "genotype NA is the one with the highest value" a "There is no genotype with the highest value"
![image](https://user-images.githubusercontent.com/25850965/37674664-5c2f007c-2c41-11e8-9c8c-f7b8668d786f.png)

**Comment by omarbenites** [comment]
?Tendrás el respectivo fieldbook?

**Comment by STOALM** [comment]
[PTYield052016_ACO_BIOT.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1838800/PTYield052016_ACO_BIOT.xlsx)

**Comment by omarbenites** [comment]
1.- Related to #249  and fixed for the next version.
2.- Bug fixed for the next version
3. NA (non asisgned) appear due inconsistencies in the data.
