### ISSUE TITLE
Elston index 2

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#181]
No genera reportes con medias "fitted":
![image](https://user-images.githubusercontent.com/25850965/37678138-29191ede-2c4b-11e8-814f-1f78a89c2a34.png)
![image](https://user-images.githubusercontent.com/25850965/37678142-30088eaa-2c4b-11e8-8889-f2a0675a9519.png)

**Comment by STOALM** [comment]
No genera reportes con medias "fitted":
![image](https://user-images.githubusercontent.com/25850965/37678138-29191ede-2c4b-11e8-814f-1f78a89c2a34.png)
![image](https://user-images.githubusercontent.com/25850965/37678142-30088eaa-2c4b-11e8-8889-f2a0675a9519.png)

**Comment by omarbenites** [comment]
Fitted features was temporarily disabled.
