### ISSUE TITLE
No crea Drought indexes

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#183]
No genera nada por este error "Permission denied":
![image](https://user-images.githubusercontent.com/25850965/37682033-61a44dea-2c56-11e8-9185-e94b409442c4.png)
![image](https://user-images.githubusercontent.com/25850965/37682039-69517428-2c56-11e8-8a47-41e99d06a8cf.png)
Adjunto libro
[PTDrought022216_ICA (1).xlsx](https://github.com/CIP-RIU/hidap_issues/files/1831144/PTDrought022216_ICA.1.xlsx)

**Comment by omarbenites** [comment]
Estuve probando y es debido a que el archivo esta corrupto por dentro. Te paso un libro, con solo el sheet fieldbook, y si genera normal.  Para los índices, se tiene que seleccionar una variable de rendimiento como TTWP u otros.
El ejemplo de Danny hay que pasarlo a un libro creado con HiDAP, seguro ellos han colocado pivot tables y otras cosas por eso el archivo esta corrupto.
[PTDT_FbDroughtICA2018.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1838097/PTDT_FbDroughtICA2018.xlsx)
