### ISSUE TITLE
PVS report

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#184]
No crea reportes para "summary_organoleptic_mother and baby"

![image](https://user-images.githubusercontent.com/25850965/37713540-3d75fb14-2ce5-11e8-9ffe-c9551fb1ebf2.png)
![image](https://user-images.githubusercontent.com/25850965/37713585-54f31f92-2ce5-11e8-94ef-22e04dafbca5.png)
Tampoco para "summary_global":
![image](https://user-images.githubusercontent.com/25850965/37715761-ddbbd562-2cea-11e8-95a5-1a8c66b2d015.png)

Adjunto libro
[PTPVS032013_JUMLA_exp1 - Copy.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1833517/PTPVS032013_JUMLA_exp1.-.Copy.xlsx)

Y no salen las opciones para llenar la información en "PVS Form Analysis"
![image](https://user-images.githubusercontent.com/25850965/37713743-d84ecac6-2ce5-11e8-9d87-a2f481c535ac.png)
Aquí sí salen:
![image](https://user-images.githubusercontent.com/25850965/37713785-f4f9c9fa-2ce5-11e8-8fe8-0fb853f60bc0.png)

**Comment by omarbenites** [comment]
Hola Jazmín, recordando en esos sheets, no había para seleccionar variables, ya que el reporte tenia que ser analizado con la hoja (Forms) completa . Respecto al error, es por una librería antigua que debe ser actualizada. Gracias por screenshots.

**Comment by omarbenites** [comment]
Self note: Include the new version of `ggrepel`. https://cran.r-project.org/bin/windows/contrib/3.4/ggrepel_0.7.0.zip :package:
