### ISSUE TITLE
Spelling 2

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#186]
![image](https://user-images.githubusercontent.com/25850965/37780958-cf2bb5ca-2dbd-11e8-97bd-a50516efee10.png)
Cambiar a Indexes

**Comment by omarbenites** [comment]
Ambos son correctos, según lei. http://grammarist.com/usage/indexes-indices/

**Comment by STOALM** [comment]
síii, pero indices no indeces, además mejor para que esté de acuerdo a lo que dice fuera en HIDAP:
![image](https://user-images.githubusercontent.com/25850965/37789216-5518a798-2dd1-11e8-8651-b012aed98f3d.png)

**Comment by omarbenites** [comment]
:+1:
