### ISSUE TITLE
mensaje múltiple 

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#187]
En genetic report creo que es suficiente que aparezca el mensaje de error sólo 1 vez. (Al subir cualquier libro sin fieldbook)
![image](https://user-images.githubusercontent.com/25850965/37793969-1ba09432-2dde-11e8-8b37-e4ea6b971197.png)

**Comment by omarbenites** [comment]
Fixed for the next version. :next_track_button: 

![image](https://user-images.githubusercontent.com/5264796/42521124-9ccd3ae2-842d-11e8-9bfb-4bd666497e46.png)
