### ISSUE TITLE
F8 - PVS

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#19]
In the sheet F8_postharvest_dormancy, some changes are needed.

This is how it is now:

![image](https://cloud.githubusercontent.com/assets/25850965/23870302/036c7c98-07f4-11e7-903b-19cfbf2a3376.png)

This is how it should be:

![image](https://cloud.githubusercontent.com/assets/25850965/23870395/442c89da-07f4-11e7-8417-7e39cdce9289.png)

PS. Refer to document attached for details

[F8.xlsx](https://github.com/omarbenites/hidap_issues/files/839319/F8.xlsx)

**Comment by STOALM** [comment]
Full names of new variables:
[Copy of Template_PVS_CIPHQ.xlsx](https://github.com/omarbenites/hidap_issues/files/839475/Copy.of.Template_PVS_CIPHQ.xlsx)

**Comment by omarbenites** [comment]
The set of new variables has been incorporated. Thnx :+1:

**Comment by STOALM** [comment]
TAPH_EV2 needs to be deleted

**Comment by STOALM** [comment]
This hasn't been solved yet:

![image](https://cloud.githubusercontent.com/assets/25850965/24256483/49ee2d0a-0fb6-11e7-8607-3427926bcabe.png)
