### ISSUE TITLE
spellling PVS (last version)

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#191]
![image](https://user-images.githubusercontent.com/25850965/39197272-b56ef25e-47a9-11e8-9dfa-487fa511d9f7.png)

Cambiar Simultanious por Simultaneous

**Comment by omarbenites** [comment]
Fixed for the next version :golf: 
![image](https://user-images.githubusercontent.com/5264796/42521434-7f6debc6-842e-11e8-8151-372a567123a7.png)
