### ISSUE TITLE
PVS in standard modules

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#192]
When uploading a fielbook in "Check fieldbooks" STANDARD, HIDAP is recognizing the sheets:

![image](https://user-images.githubusercontent.com/25850965/39197591-7ae3c9e2-47aa-11e8-9332-00f3452dbc34.png)

**Comment by omarbenites** [comment]
Fixed for the next version. :sunglasses: 
![image](https://user-images.githubusercontent.com/5264796/42516463-a79670f6-8423-11e8-9b9c-48aca0f31b5e.png)
