### ISSUE TITLE
PVS can't download fieldbook

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#193]
Adjunto libro para check y download
[PTPVS032013_JUMLA_empty - Copy.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1943487/PTPVS032013_JUMLA_empty.-.Copy.xlsx)

![image](https://user-images.githubusercontent.com/25850965/39197662-af1104dc-47aa-11e8-89be-cfa3fb1c5330.png)
![image](https://user-images.githubusercontent.com/25850965/39197684-b46aae7e-47aa-11e8-8975-c52220f749ee.png)

**Comment by omarbenites** [comment]
Issue in importing library. Now need to be declared `library::function`. Issue solved for next version.
