### ISSUE TITLE
PVS report summary_global

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#195]
Al seleccionar summary_ global para reporte de PVS:
![image](https://user-images.githubusercontent.com/25850965/39199296-b4a08bee-47ae-11e8-802f-f1458b9022e9.png)
![image](https://user-images.githubusercontent.com/25850965/39199299-b95b191a-47ae-11e8-8657-3dd49259bf28.png)
Adjunto libro (versión antigua):
[PTPVS032013_JUMLA_full.xlsx](https://github.com/CIP-RIU/hidap_issues/files/1943599/PTPVS032013_JUMLA_full.xlsx)

**Comment by omarbenites** [comment]
Actualmente solucionado.
