### ISSUE TITLE
HIDAP Online version is down

### ISSUE THREAD

**Issue by bellerbrock** [omarbenites/hidap_issues#197]
https://apps.cipotato.org/shiny/projects/hidap_sbase/

![error](https://user-images.githubusercontent.com/11297346/39323389-77a68de4-495a-11e8-959a-84e83dd963b5.png)

**Comment by omarbenites** [comment]
Hi Bryan, we have restarted our servers at CIP. It will be online again soon. Sorry for the inconvenient.
