### ISSUE TITLE
Alpha design

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#21]
Title: Maria Miki's fieldbook using Alpha design

Alpha design results:
![image](https://cloud.githubusercontent.com/assets/25850965/23875199/8c18c44a-0806-11e7-8699-ac924f370517.png)

Only two sources of variaton, there should be more.

[PTYield102016_CIPHQ_exp2.xlsx](https://github.com/omarbenites/hidap_issues/files/839607/PTYield102016_CIPHQ_exp2.xlsx)

**Comment by omarbenites** [comment]
Now fixed. Thnx :+1:
