### ISSUE TITLE
Creation of material lists with numbers and text

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#22]
Module: Fieldbook management / Material List

Description:

Hi Omar, there is one problem when I have been trying to create a field book with a material list where involving numbers and names, e.g, we put codes such as 1.40, 2.31, etc and in the field book we can see 2.31000000000006, and I dont know what is the reason. With Jazmin for now we add a letter a each number and we have a solution in the fieldboook creation, but that is no the idea. Please, try to solve the decimal issue , please.

(Verónica)

[PhD material for Astere.xlsx](https://github.com/omarbenites/hidap_issues/files/873657/PhD.material.for.Astere.xlsx)

**Comment by omarbenites** [comment]
It is a problem of excel files. To avoid it, put letters before the numbers. That solves astere's problem.
