### ISSUE TITLE
Late Blight 

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#23]
Module: Late Blight / Check fieldbook.

Doesn't calculate AUDPC, rAUDPC or SAUDPC

This error shows:

![image](https://cloud.githubusercontent.com/assets/25850965/24757079/b92b2aa4-1aa3-11e7-8a71-6d4f4dae1938.png)

[Copy of PTLate blight102015_OXAPMP_3.xlsx](https://github.com/omarbenites/hidap_issues/files/902684/Copy.of.PTLate.blight102015_OXAPMP_3.xlsx)

**Comment by omarbenites** [comment]
Now fixed. Thanks :+1:
