### ISSUE TITLE
Falla en chequeo

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#254]
Todas nuestras variables subjetivas se evaluan en una escala de 1 a 9 (todos los valores enteros entre 1 y 9 son validos). Las variables son: vir1, vir2, alt1, alt2, vv, scol, fcol, rs, rf, damr, rspr, wed. Valores como 0, 10, 11, 12, 2.5 no son validos. No se estan detectando.
![screenshot 2018-05-31 14 19 42](https://user-images.githubusercontent.com/7216359/40803268-da54d02e-64dd-11e8-8cd5-a447fed09178.png)

**Comment by omarbenites** [comment]
Solucionado para la siguiente versión.
