### ISSUE TITLE
Falla en chequeo indices

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#255]
Tenemos 3 indices en camote: HI, SHI, CI. Estos indices van de 0 a 100. No se está detectando como error valores mayores a 100.
![screenshot 2018-05-31 14 26 23](https://user-images.githubusercontent.com/7216359/40803653-c8373a52-64de-11e8-9cc5-cbf189889282.png)

**Comment by omarbenites** [comment]
Lo voy a edtiar en el archivo de ontologias de ontologias. Recuerdo que hace un tiempo nos dijiste que dejaramos abierto esos traits porque no tenia sentido que estuvieran de 0 a 100.

**Comment by omarbenites** [comment]
Solucionado para la siguiente versión.
![image](https://user-images.githubusercontent.com/5264796/42398294-f237bf0e-812e-11e8-9a46-f182f6e2bcb0.png)
