### ISSUE TITLE
etiquetas boxplot

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#256]
En el boxplot sale como etiqueta en el eje y los valores usados para el grafico, Quiza se pueda borrar.
![screenshot 2018-05-31 14 39 48](https://user-images.githubusercontent.com/7216359/40804370-a868750e-64e0-11e8-9ed0-c44b46963090.png)

**Comment by omarbenites** [comment]
Hola Raul, recuerda que puedes editar los ejes X e Y, en las cajitas de textbox.
