### ISSUE TITLE
Geographic Information

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#257]
Cambiar crop por region:
![image](https://user-images.githubusercontent.com/25850965/40923757-4e271b9c-67db-11e8-8ee3-1b29a7c1b709.png)

**Comment by omarbenites** [comment]
Corregido para la siguiente versión :potato: 
![image](https://user-images.githubusercontent.com/5264796/42397386-62799336-812b-11e8-84fa-84c9d0361c3b.png)
