### ISSUE TITLE
Hacer pull request al paquete #pepa para funcionar en el servidor

### ISSUE THREAD

**Issue by omarbenites** [omarbenites/hidap_issues#262]
Hacer pull request al pepa para que funcione en el servidor. Este debe incluir:

- Incluir 2 argumentos : `server` y `server_file` para descargar el archivo del servidor. Este se debe aplicar para los analisis de los disenos existentes (CRD, RCBD, Alpha, Augmented block design).
- Copiar las ultimas versiones de los archivos `instn/.rmd` del pepa al servidor de `hidap_sbase`.

**Comment by reyzaguirre** [comment]
pero primero ponte al dia con la ultima version

**Comment by omarbenites** [comment]
Pull request accepted.
