### ISSUE TITLE
Drought: spelling 1

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#263]
![image](https://user-images.githubusercontent.com/25850965/41668551-360794b4-7475-11e8-91d0-b1c7a60d6005.png)
Se realizaron los cambios correspondientes en el data dictionary:
![image](https://user-images.githubusercontent.com/25850965/41668665-74093ae2-7475-11e8-852f-ff5eb07e6ca3.png)

**Comment by omarbenites** [comment]
![image](https://user-images.githubusercontent.com/5264796/42397312-0e573740-812b-11e8-9ccd-7c45d66f2abe.png)


Gracias Jazmín! :+1:
