### ISSUE TITLE
Drought data dictonary

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#264]
Se corrigió el upper limit de "Canopy cover" ya que esto se registra en porcentaje:
![image](https://user-images.githubusercontent.com/25850965/41679405-b5384d78-7493-11e8-938e-fe92ff9840b4.png)
De acuerdo con el protocolo:
![image](https://user-images.githubusercontent.com/25850965/41679454-e573af82-7493-11e8-8379-a2be99604ffc.png)

**Comment by omarbenites** [comment]
Gracias Jazmincilla! :+1:
