### ISSUE TITLE
Drought: incorrect variable name

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#265]
A pesar de que se cambió en el data dictionary:
![image](https://user-images.githubusercontent.com/25850965/41681362-0337309c-749a-11e8-94ab-4c59177b39ed.png)
Y se acordó en el issue: https://github.com/CIP-RIU/hidap_issues/issues/97
Aún sale incorrecto en el fieldbook y var_list
![image](https://user-images.githubusercontent.com/25850965/41681434-348f500c-749a-11e8-8e6a-f85de7fc6994.png)
![image](https://user-images.githubusercontent.com/25850965/41681450-4186bc3c-749a-11e8-925d-17f469d3b0d7.png)
![image](https://user-images.githubusercontent.com/25850965/41681469-5334e896-749a-11e8-999b-500f18c931d7.png)

**Comment by omarbenites** [comment]
Arreglado para la siguiente versión.
![image](https://user-images.githubusercontent.com/5264796/42396955-91d50d4c-8129-11e8-82ea-ccd8e473a1eb.png)
