### ISSUE TITLE
Drought: Check fieldbook no funciona

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#266]
Error:
![image](https://user-images.githubusercontent.com/25850965/41685419-0c3b58ec-74a6-11e8-8df1-700d35143d6c.png)
![image](https://user-images.githubusercontent.com/25850965/41685425-11984516-74a6-11e8-855a-3b86bd5a0bb3.png)
Adjunto libro: 
[PTAbiotic stress072018_DALATC_exp1.xlsx](https://github.com/CIP-RIU/hidap_issues/files/2121169/PTAbiotic.stress072018_DALATC_exp1.xlsx)

**Comment by omarbenites** [comment]
Revisando el issue, he encontrado varias inconsistencias en la columna `**Scale class**`  del data diccionario, es por eso que genera errores al realizar el check en HIDAP. 

He cambiado momentaneamente los terminos por `Continuous` , `Discrete` o `Categorical` . Ver imagen.

![image](https://user-images.githubusercontent.com/5264796/42391681-cebc7de4-8115-11e8-8d2e-8b1da3cd1574.png)
