### ISSUE TITLE
Site Information

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#273]
En algunas computadoras, cuando se crea una nueva localidad, ésta no aparece para crear un nuevo fieldbook:
![image](https://user-images.githubusercontent.com/25850965/41996194-c95e2a80-7a19-11e8-9ac6-ef3a1c843166.png)
![image](https://user-images.githubusercontent.com/25850965/41996197-cb2b6d0a-7a19-11e8-8002-7994ed16916f.png)

**Comment by rarlev013** [comment]
Para no tener este tipo de inconvenientes, como la aplicación está aún en desarrollo, cada vez que se pruebe una nueva versión, borrar completamente la caché del navegador que se vaya a utilizar.
