### ISSUE TITLE
No hace reporte de LxT progeny

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#278]
Adjunto libro: 
[PTMinerals072018_CIPHQ - Copy.xlsx](https://github.com/CIP-RIU/hidap_issues/files/2186090/PTMinerals072018_CIPHQ.-.Copy.xlsx)

**Comment by omarbenites** [comment]
Fixed issue, check next patched version :+1: 

![image](https://user-images.githubusercontent.com/5264796/42956164-e56aa870-8b44-11e8-9ad6-6fa9b18d1c45.png)
