### ISSUE TITLE
Mensaje de error NC1

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#280]
<b>Cambiar a</b>: ERROR: "The number of females must be at least twice the number of males".
<b>o</b> ERROR: "The number of females must be at least twice the number of males. The material list does not meet this requirement".
![image](https://user-images.githubusercontent.com/25850965/42642135-c95c6d28-85bb-11e8-8dcf-547f97050a9e.png)

**Comment by omarbenites** [comment]
Suggestion included :potato: :sweet_potato: . Update HIDAP in a few minutes.
