### ISSUE TITLE
SFW no calcula (minerales)

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#282]
![image](https://user-images.githubusercontent.com/25850965/42659746-cc3d61b8-85ee-11e8-8f57-d77266f3c990.png)
![image](https://user-images.githubusercontent.com/25850965/42659762-da6fec38-85ee-11e8-81d5-4a67ce6b5335.png)
Se modificó el data diccionario para rango superior K, Mg, P & S:
![image](https://user-images.githubusercontent.com/25850965/42659825-178d6f1e-85ef-11e8-961f-617a2cad5997.png)
Adjunto libro: 
[PTMinerals072018_HUANCN_analisis.xlsx](https://github.com/CIP-RIU/hidap_issues/files/2190343/PTMinerals072018_HUANCN_analisis.xlsx)

**Comment by omarbenites** [comment]
The issue's been solved.
