### ISSUE TITLE
Abiotic stress, demora mucho en "Check fieldbook"

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#283]
Cuando se selecciona el file:
![image](https://user-images.githubusercontent.com/25850965/42699640-fc061e56-8686-11e8-849e-4955c8514969.png)
![image](https://user-images.githubusercontent.com/25850965/42699646-fec5517a-8686-11e8-88ca-c22f22b1be76.png)
![image](https://user-images.githubusercontent.com/25850965/42699657-05b0b254-8687-11e8-84b0-9a2ed6041477.png)
![image](https://user-images.githubusercontent.com/25850965/42699678-108d31b6-8687-11e8-8b9e-c23b5a839d8f.png)
Cuando se cambia algo en el preview: (lo mismo)
![image](https://user-images.githubusercontent.com/25850965/42700059-332a9366-8688-11e8-88dd-570218b3f572.png)
![image](https://user-images.githubusercontent.com/25850965/42700062-359fbf04-8688-11e8-81cd-bc40cf423d35.png)

**Comment by omarbenites** [comment]
Este error ya fue corregido ayer. Tienen que actualizar los paquetes, cerrar el hidap y volverlo abrir :+1: .
