### ISSUE TITLE
Abiotic stress, no calcula fieldbook

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#284]
![image](https://user-images.githubusercontent.com/25850965/42700197-a426a26c-8688-11e8-8d28-7e5764c167b1.png)
Adjunto libro: 
[PTAbiotic stress072018_AEROPC_FB - Copy.xlsx](https://github.com/CIP-RIU/hidap_issues/files/2193308/PTAbiotic.stress072018_AEROPC_FB.-.Copy.xlsx)
![image](https://user-images.githubusercontent.com/25850965/42700255-c9a933ce-8688-11e8-91da-eba15981fd6a.png)

**Comment by omarbenites** [comment]
The issue has been solved. Check next version! :+1:
