### ISSUE TITLE
Sale PVS en standard modules

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#287]
![image](https://user-images.githubusercontent.com/25850965/42900968-e8e2b5fc-8a8f-11e8-917c-f3371d3bc0cb.png)

**Comment by omarbenites** [comment]
Thanks for reporting, issue fixed in the next patched version.  :+1: 

![image](https://user-images.githubusercontent.com/5264796/42955951-4b89cb5a-8b44-11e8-81b6-2d24fc0281d0.png)
