### ISSUE TITLE
Personnel associated with the experiment AUTOFILL

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#322]
![image](https://user-images.githubusercontent.com/25850965/44989889-fc4fc500-af54-11e8-8e7f-a215473c1780.png)
Reply: 
![image](https://user-images.githubusercontent.com/25850965/44989920-17bad000-af55-11e8-8ac8-776def4003b6.png)
Previous screen:
![image](https://user-images.githubusercontent.com/25850965/44990033-6d8f7800-af55-11e8-82b6-f4758d75fa64.png)
Autofill intended:
![image](https://user-images.githubusercontent.com/25850965/44990280-2a81d480-af56-11e8-8123-9ece201f7353.png)

**Comment by cipriuhq** [comment]
Migrados a AGROFIMS project

**Comment by cipriuhq** [comment]
Migrados a AGROFIMS project
