### ISSUE TITLE
PVS: F8 sheet

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#38]
Module: Fieldbook management / check fieldbook

The formulas for the calculated variables PWL_SPT & PWL_RSPT are wrong:

![image](https://cloud.githubusercontent.com/assets/25850965/25498885/397cf4b0-2b4f-11e7-8bdf-b1edf29e490f.png)

The correct values should be:

![image](https://cloud.githubusercontent.com/assets/25850965/25499171/3c85712c-2b50-11e7-9706-26c9caa42e65.png)

**Comment by STOALM** [comment]
PWL_SPT = (FTWSPT*100)/ITW

**Comment by STOALM** [comment]
PWL_RSPT =

**Comment by omarbenites** [comment]
Vilma gaves this set of formulas : 

1. PWL_SPT = [(ITW-FTWSPT)/ITW] * 100
2. PWL_RSPT = [(ITW-FTWRSPT)/ITW ]*100

Since, 
ITW: Initial Tuber Weight
FTWSPT: Final tuber weight sprout
FTWRSPT: Final tuber weight remove sprout

Now they are fixed in HIDAP.
