### ISSUE TITLE
Hoja Fieldbook se mueve

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#39]
Cuando se hace el check en un libro la hoja fieldbook se mueve y pasa al final. No es problema pero vale la pena notarlo:
![ddd](https://cloud.githubusercontent.com/assets/7216359/25623575/ee852ab4-2f1c-11e7-83bb-7cb050422370.png)

**Comment by omarbenites** [comment]
Esto es un problema del Excel. A veces se mueve la hoja sin razon alguna.
