### ISSUE TITLE
Falla con add trial sites

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#46]
![screenshot 2017-05-03 11 03 35](https://cloud.githubusercontent.com/assets/7216359/25669806/50988cb8-2ff0-11e7-9f9e-54a43454cdcd.png)
![screenshot 2017-05-03 11 03 25](https://cloud.githubusercontent.com/assets/7216359/25669825/62612928-2ff0-11e7-836d-3ef6b7683a87.png)

**Comment by omarbenites** [comment]
Now fixed. :+1:
