### ISSUE TITLE
descargas

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#47]
Cuando descargo el template de la lista de germoplasma, esta se descarga en la carpeta asignada en mi navegador (por ejemplo escritorio).
Pero cuando descargo un fieldbook, este se descarga en la carpeta (oculta) C:\Users\reyzaguirre\AppData\Local\HIDAP\xdata\Default

Creo que sería bueno que todo se descargue en la carpeta del navegador (por una cuestión de consistencia y también de comodidad), que está más a la mano y puede ser fácil de encontrar. Un usuario primerizo le dará descargar al fieldbook y lo más probable es que no tenga ni idea de dónde buscar.

**Comment by omarbenites** [comment]
Solucionado.
