### ISSUE TITLE
nombre de libros

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#48]
Cuando no se escoge número de experimento, no se adjunta el nombre de la localidad en el nombre del libro (en la imagen SPAgronomic052017_)
Solo se adjunta el nombre de la localidad cuando se elige número de experimento (en la imagen SPAgronomic052017_CHIARA_exp1)
![screenshot 2017-05-03 14 41 08](https://cloud.githubusercontent.com/assets/7216359/25678279/cb3cfd00-300e-11e7-81f3-67e50566d2c5.png)

**Comment by omarbenites** [comment]
Que raro, acabo de hacer uno identico y no tuve problema

![image](https://cloud.githubusercontent.com/assets/5264796/25683531/36365cec-3022-11e7-8cff-c8f06f481b07.png) 

![image](https://cloud.githubusercontent.com/assets/5264796/25683599/8a61534e-3022-11e7-982c-d1d61c9efaea.png)

Hay algún detalle más para poder explicar este defecto?

**Comment by omarbenites** [comment]
Corregido
