### ISSUE TITLE
listas de clones

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#50]
Cuando se crea una lista de germoplasma y se graba en HIDAP, hay que ponerle un nombre (por ejemplo my_new_list).
![screenshot 2017-05-03 16 02 35](https://cloud.githubusercontent.com/assets/7216359/25681473/0201fef2-301a-11e7-8530-334ce11405f5.png)
Pero luego cuando se exporta en excel, siempre se exporta con el nombre Material List. Creo que sería interesante que el excel generado tenga el mismo nombre que se le dio a la lista.
![screenshot 2017-05-03 16 04 23](https://cloud.githubusercontent.com/assets/7216359/25681559/4d76fff4-301a-11e7-9809-8c97b4d2695a.png)

**Comment by omarbenites** [comment]
Now fixed. Check in the next version.
