### ISSUE TITLE
unreplicated design no está funcionando.

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#56]
Ademas, creo que sería bueno borrar el titulo (with no randomization)
Todo debe ser randomizado, aun cuando no hay repeticiones.

**Comment by reyzaguirre** [comment]
![screenshot 2017-05-06 22 47 07](https://cloud.githubusercontent.com/assets/7216359/25777811/14bdd2b8-32af-11e7-9c16-b521c247acfc.png)

**Comment by omarbenites** [comment]
Now fixed.
