### ISSUE TITLE
Lista de clones

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#57]
Cuando se usa la opción "Paste a list of clones" no funciona la opción "Select marked". Simplemente se seleccionan todos (en el ejemplo de abajo yo solo quiero un Jewel).

![screenshot 2017-05-08 11 43 31](https://cloud.githubusercontent.com/assets/7216359/25814571/9a7bdcb2-33e3-11e7-8a52-09c131a3f8dd.png)

Cuando se usa la opción de escribir el nombre en el círculo en rojo, sí funciona la opción de "Select marked"

![screenshot 2017-05-08 11 41 42](https://cloud.githubusercontent.com/assets/7216359/25814520/6b996b94-33e3-11e7-8712-e94faf90f222.png)

En cualquier caso, una vez que se han seleccionado algunos genotipos y ya aparecen en la lista "Material Selected" de abajo, ya no hay forma de borrarlos.

**Comment by omarbenites** [comment]
Cuando haces una búsqueda de varios clones usas el "Paste list of clones", el cual busca en toda la base de datos y devuelve los clones encontrados, pero no permite seleccionar.

En caso de buscar solamente 1 clon, usas el buscador pequeño (recuadro naranja) y permite seleccionar.

![image](https://cloud.githubusercontent.com/assets/5264796/25819680/5cfc3448-33f4-11e7-8f86-4219d9213038.png)
