### ISSUE TITLE
Listas con diferente formato

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#58]
Cuando se baja el template desde "Phenotype / Fieldbook management / New fieldbook", "Material Lis", , el archivo de Excel tiene una columna Numeration:
![screenshot 2017-05-08 14 16 42](https://cloud.githubusercontent.com/assets/7216359/25821951/9cbc2b94-33fc-11e7-89b0-d334e8fb5cd0.png)

Cuando se obtiene el template con la opción "Export" de "Phenotype / Material management / Manage list" no aparece la columna Numeration:
![screenshot 2017-05-08 14 41 02](https://cloud.githubusercontent.com/assets/7216359/25822029/ecede56c-33fc-11e7-9060-c7558536ea1c.png)

**Comment by omarbenites** [comment]
Arreglado.
