### ISSUE TITLE
About information

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#6]
Module: About

Description: typing errors.

1) HIDAP **means** Highly Interactive Data Analysis Platform -> HIDAP **stands** for Highly Interactive Data Analysis Platform

2) The latter via **the the** Breeding **API(BrAPI)** -> The latter via the Breeding API (BrAPI). 

3) New features include linkage with corporate and **community** databases ->New features include linkage with **corporate** and **local** databases

4) The knitr package enables the creation of repeatable **reports. The** agricolae package supports the design of field experiments and their analysis -> The knitr package enables the creation of repeatable **reports and the** agricolae package supports the design of field experiments and their analysis

Image:
![image](https://cloud.githubusercontent.com/assets/25850965/23305473/ecc184dc-fa6c-11e6-8fba-c7670680ffa0.png)

**Comment by omarbenites** [comment]
Gracias por usar Github!. Corregido :+1:
