### ISSUE TITLE
Country drop-down menu

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#62]
Title: Fieldbook management / New fieldbook/ Crop & Location / **Country & Location**

The drop-down menu should show the countries and locations in alphabetical order
![image](https://cloud.githubusercontent.com/assets/25850965/25907585/71be6700-356d-11e7-93ea-707609dca795.png)

![image](https://cloud.githubusercontent.com/assets/25850965/25908427/ccf57cf6-356f-11e7-9d03-5d63144ea3bd.png)

**Comment by omarbenites** [comment]
Now fixed. Check in the next version :man_dancing:
