### ISSUE TITLE
data transformations

### ISSUE THREAD

**Issue by reyzaguirre** [omarbenites/hidap_issues#64]
Creo que Data Transformation luciria mejor dentro de Fieldbook Management, juste después de Check Fieldbook.

**Comment by omarbenites** [comment]
Ok @reyzaguirre, vamos a considerarlo entonces.
Por otro lado, compárte este repositorio a Luka Wanjoi para que él también pueda colaborar con sugerencias o errores que encuentre. (https://github.com/omarbenites/hidap_issues)

**Comment by omarbenites** [comment]
Movido a check.
