### ISSUE TITLE
Material management: family list

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#7]
Module: Material management / family list

Description: Crop: sweetpotato, database: institutional, list: sweetpotato_pedigree, connect. When I click on some families and then click **Select marks**, nothing happens, no "material selected" shows up bellow.

Image:

![image](https://cloud.githubusercontent.com/assets/25850965/23307438/8974cac0-fa75-11e6-9dd0-dd75a7cf7e04.png)

**Comment by omarbenites** [comment]
Lo acabo de corregir, en la nueva versión ya esta listo.
