### ISSUE TITLE
Requests for new installer (64 and 32)

### ISSUE THREAD

**Issue by STOALM** [omarbenites/hidap_issues#81]
1) Fix issues #77  & #78 

2) Replace PVS documentation (sent via email)

3) Add PVS documentation (sent via email)

*Use these names:
-Participatory Varietal Selection: Dictionary
-Participatory Varietal Selection: Selection Criteria

![image](https://cloud.githubusercontent.com/assets/25850965/26317486/3d339068-3edd-11e7-81c8-dfc0fe8c65bc.png)

**Comment by omarbenites** [comment]
Both 64-bits and 32-bits installers are already in your personal folder. Please check it. :desktop_computer:
